### ISSUE TITLE
New installs of DSF 20.3.0.8 return error 5700 when first used in a VeriStand project

### ISSUE THREAD

**Issue by ryanpoulos** [ni/niveristand-data-sharing-framework-custom-device#23]
**Describe the bug**
The NI package installer for DSF 20.3.0.8 does not create the 'Components' folder under each target folder in the VeriStand\Custom Devices\Data Sharing Framework directory. Since the DSF looks for this folder to load user Component PPLs, it throws error 5700 (Components directory missing error) when the custom device is first loaded in VeriStand System Explorer.

**To Reproduce**
1. Install DSF 20.3.0.8.
2. Create a new VeriStand project and add the DSF custom device. Error 5700 will be thrown due to the folder not being found.

**Expected behavior**
The folders should be there so that the DSF is happy.

**Screenshots**
![image](https://user-images.githubusercontent.com/10538685/94463256-44686280-0182-11eb-82f8-3478d3bf7f10.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 20.3.0.8

**Comment by buckd** [comment]
Are you only installing the DSF nipkg or are you also installing the nipkg from the [plugins repo](https://github.com/ni/niveristand-data-sharing-framework-custom-device-plugins)?

**Comment by ryanpoulos** [comment]
I only had installed the custom device package. There is no error with both packages, but the DSF package alone will cause this error.

**Comment by rtzoeller** [comment]
I see two possible resolutions:
1. We update the custom device to not error if this folder doesn't exist.
2. We update the package to create the folder.

I think we should do both.

File-based nipkgs can't natively create empty folders, so we could either install a text file alerting people of the purpose of the folder, or add a custom instructions file to the package which creates the folder. I'd prefer the former, because it's almost certainly easier.
